config/routes.rb
Rails.application.routes.draw do
  root("posts#index")
  get("/about", to: "posts#about")
  #resources :articles, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 6, maximum: 140}
end

app/models/user.rb
class EmailAddrValid < ActiveModel::Validator
  def validate(usrrec)
    unless usrrec.email.empty? || usrrec.email =~ /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      usrrec.errors.add :base, "Invalid email address format"
    end
  end
end

class User < ApplicationRecord
  validates :username, presence: true, length: { in: 3..20 }, uniqueness: { case_sensitive: false }
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }
  validates_with EmailAddrValid
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  
  def index
    @articles = Article.all
  end
  
  def show
    #byebug
  end
  
  def new
    @article = Article.new
  end
  
  def create
    #render plain: params[:article]
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Save successful!"
      redirect_to article_path(@article)
    else
      render "new"
    end
  end
  
  def edit
    set_article
  end
  
  def update
    
    if @article.update(article_params)
      flash[:notice] = "Success!"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @article.destroy
    redirect_to articles_path
  end
  
  private
  
  def set_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    # White-list the elements allowed to change
    params.require(:article).permit(:title, :description)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/_errorsave.html.erb
        <% if @article.errors.full_messages.count>0 %>
        <div class="container">
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <h4 class = "alert-heading">Not saved because:</h4>
            <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert">
            </button>
          </div>
        </div>
        <% end %>

app/views/articles/_form.html.erb
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-10">
        <%= form_with(model: @article, local: true) do |f| %>
          <div class="form-group row mt-4">
            <%= f.label :title, class: "col-2 col-form-label" %>
            <div class="col-10">
              <%= f.text_field :title, class: "form-control" %>
            </div>
          </div>
          
          <div class="form-group row mt-4">
            <%= f.label :description,  class: "col-2 col-form-label" %>
            <div class="col-10">
              <%= f.text_area :description, rows: 10, class: "form-control" %>
            </div>
          </div>
          <div class="form-group col-2 mx-auto mt-4">
            <%= f.submit class: "btn btn-outline-light btn-lg" %>
          </div>
        <% end %>
        </div>
      </div>
      <div class = "row justify-content-center mt-10 mb-3">
        <%= link_to '[ Close ]', articles_path, class: "btn" %>
      </div>
    </div>

app/views/articles/edit.html.erb
  <h1 class="text-center mt-4">Edit Article <%= @article.id %></h1>
  <%= render 'errorsave' %>
  <%= render 'form' %>

app/views/articles/index.html.erb
  <h1 class="text-center mt-4">Articles</h1>

  <div class="container">
    <% @articles.each do |a| %>
    <div class="row justify-content-md-center mt-4">
      <div class="col-8">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            <%= link_to a.title, article_path(a), class: "text-success" %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= rand(1000) %> views</h5>
            <p class="card-text"><%= truncate a.description, length: 32 %></p>
            <%= link_to "View", article_path(a.id), class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_article_path(a.id), class: "btn btn-outline-primary" %>
            <%= link_to "Delete", article_path(a.id), method: :delete, data: {confirm: "Delete: Are you sure?"}, class: "btn btn-outline-warning" %>
          </div>
          <div class="card-footer text-muted">
            <small>Updated <%= time_ago_in_words(a.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

app/views/articles/new.html.erb
  <h1 class="text-center mt-4">New Article</h1>
  <%= render 'errorsave' %>
  <%= render 'form' %>

app/views/articles/show.html.erb
  <h2 class="text-center mt-4"><%= @article.title %></h2>
  <div class="container">
    <div class="row justify-content-md-center mt-4">
      <div class="col-8">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, updated <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
          <div class="card-body">
            <div class="card-text text-start"><%= simple_format(@article.description) %></div>
          </div>
          <div class="card-footer text-muted">
            <%= link_to "Edit", edit_article_path(@article.id), class: "btn btn-outline-primary" %>
            <%= link_to "Delete", article_path(@article.id), method: :delete, data: {confirm: "Delete: Are you sure?"}, class: "btn btn-outline-warning" %>
          </div>
        </div>
      </div>
    </div>
    <div class = "row justify-content-center mt-10">
      <%= link_to '[ Close ]', articles_path, class: "btn" %>
    </div>
  </div>

app/views/layouts/_abfooter.html.erb
    <footer id="sticky-footer" class = "py-4 bg-dark text-white-50">
      <div class="container text-center">
        <small>Copyright &copy; <%= link_to "pgstodda", "http://www.stoddard.id.au", class: "text-white-50" %></small>
      </div>
    </footer>

app/views/layouts/_messages.html.erb
    <div id="page-content">
      <div class="container">
        <% flash.each do |key, msg| %>
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= msg %>
            <button class="btn-close" data-bs-dismiss="alert">
            </button>
          </div>
        <% end %>
      </div>
    </div>

app/views/layouts/_nav.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to "ALPHA-BLOG", root_path, class: "navbar-brand", id: "ablogo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "About", about_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Articles
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "Create new article", new_article_path, class: "dropdown-item" %></li>
                <li><%= link_to "List of articles", articles_path, class: "dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Home", root_path, class: "dropdown-item" %></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Login</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/nav' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/abfooter' %>
  </body>
</html>

app/views/posts/about.html.erb
<div container>
  <h1>About Alpha</h1>
  <h2>Version 1.0</h2>
</div>

app/views/posts/index.html.erb
    <div class="container" id="home-container">
      <div class="bg-light p-5 rounded-lg m-3 text-center" id="home-splash">
        <h1 class="display-4">Alpha-Blog</h1>
        <p class="lead">Rails course exercise</p>
        <hr class="my-4">
        <p>Create, Read, Update and Delete articles</p>
        <a class="btn btn-success btn-lg" href="articles" role="button">Get started</a>
      </div>
    </div>
    <p>